---
# tasks file for vcd_vapp_vm_snapshot
#
- name: create vm snapshot
  vcd_vapp_vm_snapshot:
    user: acmeadmin
    org: Acme
    password: VMware1!
    vdc_name: ACME_PAYG
    vapp_name: acme_vapp
    vms:
      - name: sample-2
        mem_snapshot: true
        snapshot_name: snap_sample
    state: present
  register: output

- name: create vm snapshot output
  debug:
    msg: '{{ output }}'

- name: list vm snapshot
  vcd_vapp_vm_snapshot:
    user: acmeadmin
    org: Acme
    password: VMware1!
    vdc_name: ACME_PAYG
    vapp_name: acme_vapp
    vms:
      - name: sample-2
    operation: list
  register: output

- name: list vm snapshot output
  debug:
    msg: '{{ output }}'

- name: revert vm snapshot
  vcd_vapp_vm_snapshot:
    user: acmeadmin
    org: Acme
    password: VMware1!
    vdc_name: ACME_PAYG
    vapp_name: acme_vapp
    vms:
      - name: sample-2
    operation: revert
  register: output

- name: revert vm snapshot output
  debug:
    msg: '{{ output }}'

- name: list vm snapshot
  vcd_vapp_vm_snapshot:
    user: acmeadmin
    org: Acme
    password: VMware1!
    vdc_name: ACME_PAYG
    vapp_name: acme_vapp
    vms:
      - name: sample-2
    operation: list
  register: output

- name: list vm snapshot output
  debug:
    msg: '{{ output }}'

- name: delete vm snapshot
  vcd_vapp_vm_snapshot:
    user: acmeadmin
    org: Acme
    password: VMware1!
    vdc_name: ACME_PAYG
    vapp_name: acme_vapp
    vms:
      - name: sample-2
    state: absent
  register: output

- name: delete vm snapshot output
  debug:
    msg: '{{ output }}'