---
# tasks file for vcd_edge_gateway

- name: create edge gateway
  vcd_vdc_gateway:
    org_name: Acme
    vdc_name: ACME_PAYG
    gateway_name: test-gateway
    gateway_backing_config: compact
    external_networks:
      - external-network
    state: present
  register: output

- name: create edge gateway output
  debug:
    msg: '{{ output }}'

- name: update edge gateway
  vcd_vdc_gateway:
    org_name: Acme
    vdc_name: ACME_PAYG
    gateway_name: test-gateway
    new_gateway_name: test-gateway-01
    ha_enabled: true
    state: update
  register: output

- name: update edge gateway output
  debug:
    msg: '{{ output }}'

- name: update edge gateway
  vcd_vdc_gateway:
    org_name: Acme
    vdc_name: ACME_PAYG
    gateway_name: test-gateway
    ext_net_subnet_allocated_ip_pool:
      external-network: 10.176.3.20-10.176.3.25
    operation: update_ip_pool
  register: output

- name: update edge gateway
  debug:
    msg: '{{ output }}'

- name: update edge gateway
  vcd_vdc_gateway:
    org_name: Acme
    vdc_name: ACME_PAYG
    gateway_name: test-gateway
    ext_net_to_participated_subnet_with_ip_settings:
      external-network:
          172.17.11.1/24: 172.17.11.102
    operation: add_network
  register: output

- name: update edge gateway
  debug:
    msg: '{{ output }}'

- name: update edge gateway
  vcd_vdc_gateway:
    org_name: Acme
    vdc_name: ACME_PAYG
    gateway_name: test-gateway
    external_networks:
      - external-network
    operation: remove_network
  register: output

- name: update edge gateway
  debug:
    msg: '{{ output }}'

- name: delete edge gateway
  vcd_vdc_gateway:
    org_name: Acme
    vdc_name: ACME_PAYG
    gateway_name: test-gateway
    state: absent
  register: output

- name: delete edge gateway output
  debug:
    msg: '{{ output }}'