---
# tasks file for vcd_vapp_vm_disk


- name: add a disk
  vcd_vapp_vm_disk:
    user: acmeadmin
    password: VMware1!
    org: Acme
    vm_name: centos
    vapp: vApp_system_2
    vdc: ACME_PAYG
    disks:
      - size: 1
        controller: lsilogic
      - size: 1
        controller: VirtualSCSI
    state: present
  register: myResult

- name: Show the data
  debug:
    msg: "{{ myResult }}"

- name: update a disk
  vcd_vapp_vm_disk:
    user: acmeadmin
    password: VMware1!
    org: Acme
    vm_name: centos
    vapp: vApp_system_2
    vdc: ACME_PAYG
    disks:
      - name: Hard disk 1
        size: 3
    state: update
  register: myResult

- name: Show the data
  debug:
    msg: "{{ myResult }}"

- name: Read my disks
  vcd_vapp_vm_disk:
    user: acmeadmin
    password: VMware1!
    org: Acme
    vm_name: centos
    vapp: vApp_system_2
    vdc: ACME_PAYG
    operation: read
  register: myResult

- name: Show the data
  debug:
    msg: "{{ myResult }}"

- name: delete my disks
  vcd_vapp_vm_disk:
    user: acmeadmin
    password: VMware1!
    org: Acme
    vm_name: centos
    vapp: vApp_system_2
    vdc: ACME_PAYG
    disks:
      - name: Hard disk 1
    state: absent
  register: myResult

- name: Show the data
  debug:
    msg: "{{ myResult }}"
